server:
    port: 5000
    error:
        include-message: always
spring:
    jpa:
        hibernate:
            ddl-auto: update
            format_sql: true
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database: mysql
        show-sql: true
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:contact_db}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:pass}
        driver-class-name: com.mysql.cj.jdbc.Driver
